### ISSUE TITLE
React bindings?

### ISSUE THREAD

**Issue by NayamAmarshe** [AnnikaV9/starfield.js#2]
Hi any plans to make React bindings for this? Would be cool to see :D

**Comment by AnnikaV9** [comment]
Yes! I'll implement it soon :)

**Comment by NayamAmarshe** [comment]
Thank you! :D

**Comment by AnnikaV9** [comment]
I'm not fluent in react (not that sure what the standard is), could you check if the below would appropriate for the latest changes? Is it supposed to be plug and play or just an example?
```js
import React, { useEffect, useRef } from "react";
import Starfield from "./starfield";

const StarfieldComponent = (props) => {
  const containerRef = useRef(null);
  const originRef = useRef(null);

  useEffect(() => {
    if (containerRef.current && originRef.current) {
      Starfield.setup({
        ...props,
        container: containerRef.current,
        originElement: originRef.current,
      });
    }

    return () => {
      Starfield.cleanup();
    };
  }, [props]);

  return (
    <div
      ref={containerRef}
      style={{ position: "relative", width: "100%", height: "100%" }}
    >
      <div
        ref={originRef}
        style={{
          position: "absolute",
          left: "50%",
          top: "50%",
          width: "100px",
          height: "100px",
          marginLeft: "-50px",
          marginTop: "-50px",
          borderRadius: "50%",
          background: "rgba(255, 255, 255, 0.1)",
          cursor: "pointer",
          pointerEvents: "auto",
        }}
      >
      </div>
      {props.children}
    </div>
  );
};

export default StarfieldComponent;
```

**Comment by AnnikaV9** [comment]
I've never written bindings for distribution before, so a little lost. Maybe someone with better react experience should implement and maintain it.

**Comment by NayamAmarshe** [comment]
@AnnikaV9 Thanks for the help! I was actually doing something similar. Starfield works with React just fine, so I don't think there's any need for an exclusive binding. However, I was just a little lost on how to make it work with a background color. I tried adding a fixed div with full height and width, but it doesn't seem to work.

```jsx
<div className="relative flex min-h-screen w-screen flex-col items-center justify-center bg-bg">
      <div className="fixed h-screen w-screen" ref={starfieldRef} />
      <LinkForm />
    </div>
```

**Comment by AnnikaV9** [comment]
Currently it forces a black canvas, so a custom background color won't be possible. I'll add an option for it

**Comment by AnnikaV9** [comment]
I've pushed a change that adds a `canvasColor` option, can you check if it's a viable solution for you?

**Comment by NayamAmarshe** [comment]
Yes, it's working. Thanks a lot!
